//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.3
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ./parser/grammer/RcpDoc.g4 by ANTLR 4.9.3

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IRcpDocListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.3")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class RcpDocBaseListener : IRcpDocListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="RcpDocParser.rcpParamBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRcpParamBlock([NotNull] RcpDocParser.RcpParamBlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RcpDocParser.rcpParamBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRcpParamBlock([NotNull] RcpDocParser.RcpParamBlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RcpDocParser.rcpParamName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRcpParamName([NotNull] RcpDocParser.RcpParamNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RcpDocParser.rcpParamName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRcpParamName([NotNull] RcpDocParser.RcpParamNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RcpDocParser.rcpParamTypeBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRcpParamTypeBlock([NotNull] RcpDocParser.RcpParamTypeBlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RcpDocParser.rcpParamTypeBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRcpParamTypeBlock([NotNull] RcpDocParser.RcpParamTypeBlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RcpDocParser.typeValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeValue([NotNull] RcpDocParser.TypeValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RcpDocParser.typeValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeValue([NotNull] RcpDocParser.TypeValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RcpDocParser.supportedObjectValues"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSupportedObjectValues([NotNull] RcpDocParser.SupportedObjectValuesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RcpDocParser.supportedObjectValues"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSupportedObjectValues([NotNull] RcpDocParser.SupportedObjectValuesContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RcpDocParser.supportedObjectValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSupportedObjectValue([NotNull] RcpDocParser.SupportedObjectValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RcpDocParser.supportedObjectValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSupportedObjectValue([NotNull] RcpDocParser.SupportedObjectValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RcpDocParser.paramDesc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParamDesc([NotNull] RcpDocParser.ParamDescContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RcpDocParser.paramDesc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParamDesc([NotNull] RcpDocParser.ParamDescContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RcpDocParser.typesJsonBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypesJsonBlock([NotNull] RcpDocParser.TypesJsonBlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RcpDocParser.typesJsonBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypesJsonBlock([NotNull] RcpDocParser.TypesJsonBlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RcpDocParser.jsonKeyValuePair"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterJsonKeyValuePair([NotNull] RcpDocParser.JsonKeyValuePairContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RcpDocParser.jsonKeyValuePair"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitJsonKeyValuePair([NotNull] RcpDocParser.JsonKeyValuePairContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RcpDocParser.jsonValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterJsonValue([NotNull] RcpDocParser.JsonValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RcpDocParser.jsonValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitJsonValue([NotNull] RcpDocParser.JsonValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RcpDocParser.jsonObject"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterJsonObject([NotNull] RcpDocParser.JsonObjectContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RcpDocParser.jsonObject"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitJsonObject([NotNull] RcpDocParser.JsonObjectContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
